export enum ErrorCode {
  VALIDATION_ERROR = "VALIDATION_ERROR",
  UNAUTHORIZED = "UNAUTHORIZED",
  FORBIDDEN = "FORBIDDEN",
  NOT_FOUND = "NOT_FOUND",
  DUPLICATE_REQUEST = "DUPLICATE_REQUEST",
  INTERNAL_ERROR = "INTERNAL_ERROR",
  BAD_REQUEST = "BAD_REQUEST",
  RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED",
  BLOG_NOT_FOUND = "BLOG_NOT_FOUND",
  ARTICLE_NOT_FOUND = "ARTICLE_NOT_FOUND",
  BOOK_NOT_FOUND = "BOOK_NOT_FOUND",
  CAREER_TIMELINE_NOT_FOUND = "CAREER_TIMELINE_NOT_FOUND",
  ACHIEVEMENT_NOT_FOUND = "ACHIEVEMENT_NOT_FOUND",
  DOWNLOAD_NOT_FOUND = "DOWNLOAD_NOT_FOUND",
  PROJECT_NOT_FOUND = "PROJECT_NOT_FOUND",
  SKILL_NOT_FOUND = "SKILL_NOT_FOUND",
  TESTIMONIAL_NOT_FOUND = "TESTIMONIAL_NOT_FOUND",
  PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS",
  INVALID_TOKEN = "INVALID_TOKEN",
  TOKEN_EXPIRED = "TOKEN_EXPIRED",
}

export const ErrorMessages: Record<ErrorCode, string> = {
  [ErrorCode.VALIDATION_ERROR]: "Validation failed",
  [ErrorCode.UNAUTHORIZED]: "Unauthorized",
  [ErrorCode.FORBIDDEN]: "Forbidden",
  [ErrorCode.NOT_FOUND]: "Resource not found",
  [ErrorCode.DUPLICATE_REQUEST]: "Duplicate request",
  [ErrorCode.INTERNAL_ERROR]: "Internal server error",
  [ErrorCode.BAD_REQUEST]: "Bad request",
  [ErrorCode.RATE_LIMIT_EXCEEDED]: "Too many requests",
  [ErrorCode.BLOG_NOT_FOUND]: "Blog post not found",
  [ErrorCode.ARTICLE_NOT_FOUND]: "Article not found",
  [ErrorCode.BOOK_NOT_FOUND]: "Book not found",
  [ErrorCode.CAREER_TIMELINE_NOT_FOUND]: "Career timeline entry not found",
  [ErrorCode.ACHIEVEMENT_NOT_FOUND]: "Achievement not found",
  [ErrorCode.DOWNLOAD_NOT_FOUND]: "Download not found",
  [ErrorCode.PROJECT_NOT_FOUND]: "Project not found",
  [ErrorCode.SKILL_NOT_FOUND]: "Skill not found",
  [ErrorCode.TESTIMONIAL_NOT_FOUND]: "Testimonial not found",
  [ErrorCode.PROFILE_NOT_FOUND]: "Site profile not found",
  [ErrorCode.INVALID_CREDENTIALS]: "Invalid credentials",
  [ErrorCode.EMAIL_ALREADY_EXISTS]: "Email already exists",
  [ErrorCode.INVALID_TOKEN]: "Invalid token",
  [ErrorCode.TOKEN_EXPIRED]: "Token expired",
};

export const StatusCodeMap: Record<ErrorCode, number> = {
  [ErrorCode.VALIDATION_ERROR]: 400,
  [ErrorCode.UNAUTHORIZED]: 401,
  [ErrorCode.FORBIDDEN]: 403,
  [ErrorCode.NOT_FOUND]: 404,
  [ErrorCode.DUPLICATE_REQUEST]: 409,
  [ErrorCode.INTERNAL_ERROR]: 500,
  [ErrorCode.BAD_REQUEST]: 400,
  [ErrorCode.RATE_LIMIT_EXCEEDED]: 429,
  [ErrorCode.BLOG_NOT_FOUND]: 404,
  [ErrorCode.ARTICLE_NOT_FOUND]: 404,
  [ErrorCode.BOOK_NOT_FOUND]: 404,
  [ErrorCode.CAREER_TIMELINE_NOT_FOUND]: 404,
  [ErrorCode.ACHIEVEMENT_NOT_FOUND]: 404,
  [ErrorCode.DOWNLOAD_NOT_FOUND]: 404,
  [ErrorCode.PROJECT_NOT_FOUND]: 404,
  [ErrorCode.SKILL_NOT_FOUND]: 404,
  [ErrorCode.TESTIMONIAL_NOT_FOUND]: 404,
  [ErrorCode.PROFILE_NOT_FOUND]: 404,
  [ErrorCode.INVALID_CREDENTIALS]: 401,
  [ErrorCode.EMAIL_ALREADY_EXISTS]: 409,
  [ErrorCode.INVALID_TOKEN]: 401,
  [ErrorCode.TOKEN_EXPIRED]: 401,
};
