export const defaultProfile = {
  firstName: "Edeh",
  middleName: "Chinedu",
  lastName: "Daniel",
  alias: "RabbitDaCoder",
  tagline: "Full-Stack Engineer & Software Developer",
  subTagline: "PERN Stack - React - TypeScript - DevOps - Blockchain",
  fullHeadline:
    "Full-Stack Software Engineer | PERN Stack | React & TypeScript | DevOps | Blockchain | IoT",
  bio1:
    "I build digital experiences that live at the intersection of engineering and design, from IoT water systems to blockchain startups and production web platforms.",
  bio2:
    "Currently pursuing Computer and Robotics Education at the University of Nigeria, Nsukka, while delivering web, mobile, and robotics solutions.",
  pullQuote: "I believe great software should feel as good as it works.",
  availability: "Available for new projects",
  email: "edehchinedu59@gmail.com",
  phone: "+234 803 702 0923",
  location: "Enugu, Nigeria",
  locationShort: "Enugu, Nigeria",
  timezone: "WAT / UTC+1",
  github: "https://github.com/RabbitDaCoder",
  linkedin: "https://www.linkedin.com/in/edehchinedu20",
  youtube: "https://youtube.com/@RabbitDaCoder",
  twitter: "https://x.com/EdehChinedu20",
  portfolio: "https://edehchinedu.dev",
  calendly: "https://calendly.com/edehchinedu59",
};

export const defaultProjects = [
  {
    name: "HydroSense",
    slug: "hydrosense",
    description: "IoT-powered water automation system with live dashboards for monitoring, billing, analytics, and reservoir automation.",
    longDescription: "Lead developer building an IoT-powered water automation system using React, TypeScript, Go, and ESP32 hardware.",
    stack: ["React", "TypeScript", "Go", "ESP32", "IoT", "React Native"],
    tags: ["React", "TypeScript", "Go", "ESP32", "IoT", "React Native"],
    projectType: "team",
    featured: true,
    typographicMark: "H2O",
    order: 1,
    published: true,
  },
  {
    name: "StarkDCA",
    slug: "starkdca",
    description: "Automated Bitcoin Dollar-Cost Averaging on Starknet.",
    longDescription: "Co-founded and built StarkDCA, a non-custodial automated Bitcoin DCA platform on Starknet with Cairo smart contracts and a full-stack web app.",
    stack: ["Cairo", "Starknet", "React", "TypeScript", "Node.js", "Redis"],
    tags: ["Cairo", "Starknet", "React", "TypeScript", "Node.js", "Redis"],
    projectType: "startup",
    liveUrl: "https://www.starkdca.xyz",
    githubUrl: "https://github.com/RabbitDaCoder/StarkDCA",
    featured: true,
    typographicMark: "DCA",
    order: 2,
    published: true,
  },
  {
    name: "Amanpulo Resort",
    slug: "amanpulo",
    description: "Luxury hotel reservation system with receipts, email confirmations, admin dashboard, and live chat.",
    longDescription: "Full-stack MERN reservation system for Amanpulo Private Island Resort with a premium booking experience.",
    stack: ["React", "Vite", "Tailwind CSS", "Node.js", "Express", "MongoDB"],
    tags: ["React", "Vite", "Tailwind CSS", "Node.js", "Express", "MongoDB"],
    projectType: "freelance",
    liveUrl: "https://amanpuloresort.com",
    githubUrl: "https://github.com/RabbitDaCoder/Amanpulo",
    featured: true,
    typographicMark: "AMN",
    order: 3,
    published: true,
  },
  {
    name: "VTE Faculty Website",
    slug: "vte-faculty",
    description: "Led a 6-person team to build the first version of the VTE faculty website.",
    longDescription: "React and Tailwind CSS faculty website with Git collaboration, accessibility, and deployment.",
    stack: ["React.js", "Tailwind CSS", "Git"],
    tags: ["React.js", "Tailwind CSS", "Git"],
    projectType: "client",
    liveUrl: "https://vte-website.netlify.app/",
    featured: false,
    typographicMark: "UNN",
    order: 4,
    published: true,
  },
];

export const defaultSkills = [
  ["React.js", "FRONTEND"],
  ["Next.js", "FRONTEND"],
  ["TypeScript", "FRONTEND"],
  ["Tailwind CSS", "FRONTEND"],
  ["Node.js", "BACKEND"],
  ["Express.js", "BACKEND"],
  ["MongoDB", "DATABASE"],
  ["PostgreSQL", "DATABASE"],
  ["Redis", "DATABASE"],
  ["Docker", "DEVOPS"],
  ["GitHub Actions", "DEVOPS"],
  ["Cairo", "BLOCKCHAIN"],
  ["Starknet", "BLOCKCHAIN"],
  ["Three.js", "THREED"],
  ["Figma", "TOOLS"],
].map(([name, category], index) => ({ name, category, order: index + 1 }));

export const defaultCareer = [
  {
    id: "aptech",
    type: "EDUCATION",
    title: "Software Engineering",
    organisation: "APTECH Computer Education",
    date: "Oct 2022 - Sept 2023",
    startDate: new Date("2022-10-01"),
    endDate: new Date("2023-09-01"),
    current: false,
    description: "Comprehensive software engineering training covering programming languages, IoT, web development, and systems design.",
    points: ["Studied Java, C, C#, Dart, Flutter, PHP, Python, IoT, and web development."],
    keySkills: ["Java", "C", "C#", "Dart", "Flutter", "PHP", "Python", "IoT"],
    order: 1,
  },
  {
    id: "starkdca",
    type: "BLOCKCHAIN",
    title: "Smart Contract Developer & Software Engineer",
    organisation: "StarkDCA",
    date: "2025 - Present",
    startDate: new Date("2025-01-01"),
    endDate: null,
    current: true,
    description: "Co-founded StarkDCA, an automated Bitcoin DCA platform on Starknet.",
    points: ["Built Cairo smart contracts, backend services, and a React TypeScript frontend."],
    keySkills: ["Cairo", "Starknet", "React", "TypeScript", "Node.js"],
    order: 2,
  },
  {
    id: "hydrosense-work",
    type: "JOB",
    title: "Lead Developer",
    organisation: "HydroSense",
    date: "July 2025 - Present",
    startDate: new Date("2025-07-01"),
    endDate: null,
    current: true,
    description: "Lead developer on an IoT-powered Smart Water Distribution System.",
    points: ["Built dashboards for live monitoring, billing, analytics, and reservoir automation."],
    keySkills: ["React", "TypeScript", "Go", "ESP32", "IoT"],
    order: 3,
  },
];

export const defaultAchievements = [
  {
    id: "starkdca-launch",
    title: "Co-Founded StarkDCA",
    description: "Co-founded and shipped a non-custodial automated Bitcoin DCA platform on Starknet.",
    date: "2025",
    order: 1,
  },
  {
    id: "droinetech-founding",
    title: "Founded DroineTech",
    description: "Launched a tech agency delivering web, mobile, and robotics solutions.",
    date: "July 2025",
    order: 2,
  },
  {
    id: "hydrosense-iot",
    title: "HydroSense IoT System",
    description: "Led development of an IoT water automation system integrating ESP32 hardware and live dashboards.",
    date: "July 2025",
    order: 3,
  },
];

export const defaultTestimonials = [
  {
    id: "maryann",
    name: "Eloike Maryann",
    role: "CEO",
    designation: "CEO",
    company: "ChyChyAgent",
    quote: "I thought it was impossible to make a website as beautiful as our product, but RabbitDaCoder proved me wrong.",
    initials: "EM",
    order: 1,
    published: true,
  },
  {
    id: "chibuzo",
    name: "Chibuzo Daniel",
    role: "School President",
    designation: "School President",
    company: "VTE Faculty - UNN Nsukka",
    quote: "I have never met a web developer who truly cares about their clients success like RabbitDaCoder does.",
    initials: "CD",
    order: 2,
    published: true,
  },
];

export const defaultPolaroids = [
  { id: "p1", src: "", alt: "Working on HydroSense IoT hardware", caption: "Building H2O", rotation: -4.2, order: 1, published: true },
  { id: "p2", src: "", alt: "Coding session late at night", caption: "Late night grind", rotation: 2.8, order: 2, published: true },
  { id: "p3", src: "", alt: "StarkDCA blockchain development", caption: "On-chain", rotation: 3.6, order: 3, published: true },
];

export const defaultDownloads = [
  {
    label: "Edehs-Resume.pdf",
    fileUrl: "/Edehs-Resume.pdf",
    version: "v3.0",
    headline: "Full-Stack Software Engineer | PERN Stack | React & TypeScript | DevOps | Blockchain | IoT",
    lastUpdated: "March 2026",
    active: true,
    downloads: 0,
  },
];

export const defaultBlogPosts = [
  {
    title: "Mastering GSAP ScrollTrigger for Web Animations",
    slug: "mastering-gsap-scrolltrigger",
    content: "Deep dive into advanced scroll-triggered animations with practical examples.",
    excerpt: "Deep dive into advanced scroll-triggered animations with practical examples.",
    category: "Web Development",
    tags: ["Animation", "GSAP", "JavaScript"],
    readTime: 8,
    published: false,
    featured: false,
    views: 0,
  },
  {
    title: "Building 3D Web Experiences with React Three Fiber",
    slug: "building-3d-web-experiences-r3f",
    content: "Learn how to integrate Three.js into React applications efficiently.",
    excerpt: "Learn how to integrate Three.js into React applications efficiently.",
    category: "Web Development",
    tags: ["3D", "React", "Three.js"],
    readTime: 12,
    published: false,
    featured: false,
    views: 0,
  },
];

export const defaultBooks = [
  {
    title: "The Web Development Handbook",
    slug: "web-development-handbook",
    description: "A comprehensive guide to modern web development practices and patterns.",
    price: 0,
    published: false,
    featured: false,
  },
  {
    title: "Animation Mastery",
    slug: "animation-mastery",
    description: "Advanced techniques for creating polished web animations.",
    price: 0,
    published: false,
    featured: false,
  },
];
